name: PHPCS

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.3'] # Add PHP versions to test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: composer install --no-progress --no-suggest

            - name: Run PHPCS
              run: vendor/bin/php-cs-fixer fix --dry-run
