name: Rector

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    rector:
        name: Rector Code Refactoring
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.3']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install dependencies
              run: composer install --no-progress --no-suggest

            - name: Run Rector
              run: vendor/bin/rector process --dry-run
